/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavbar: typeof import('./src/components/BottomNavbar.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    NoRoutesHistory: typeof import('./src/components/NoRoutesHistory.vue')['default']
    RouteMap: typeof import('./src/components/RouteMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
